config/routes.rb
Rails.application.routes.draw do

  root 'templates#index'
  resources :templates

end

app/models/template.rb
class Template < ActiveRecord::Base
  validates :name, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController

  def new
    @template = Template.new
  end

  def create
    @template = Template.new(template_params)
    if @template.save
      flash[:notice] = 'Template successfully created'
      redirect_to templates_path
    else
      flash[:alert] = 'Template create error'
      render action: :new
    end
  end

  def show
    @template = Template.find(params[:id])
    render inline: @template.body, locals: { template: @template },  layout: false
  end

  def index
    @templates = Template.all
  end

  private

    def template_params
      params.require(:template).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Dinoviews
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      = render 'shared/flash'
      = yield

app/views/shared/_errors.html.haml
-if object.errors.any?
  .panel.panel-danger
    .panel-body
      %strong.text-danger
        = "#{pluralize(object.errors.count, "error")} prohibited this post from being saved:"
      %ul
        -object.errors.to_hash.each do |key, value|
          %li
            %strong
              =key
              \:
            -value.each do |v|
              =v

app/views/shared/_flash.html.haml
-flash.each do |type, message|
  -if type == 'notice'
    .alert.alert-success
      = message
  -elsif type == 'alert'
    .alert.alert-danger
      = message

app/views/templates/index.html.haml
.row
  .col-md-12
    %h1 Templates list
.row
  .col-md-12.right
    =link_to 'Add template', new_template_path, class: 'btn btn-info'
.row
  .col-md-12
    %table.table.table-bordered.table-hover
      %thead
        %tr
          %th Id
          %th Name
      - @templates.each do |template|
        %tbody
          %tr
            %td= template.id
            %td= link_to template.name, template_path(template)

app/views/templates/new.html.haml
.row
  .col-md-6
    =render partial: 'shared/errors', locals: {object: @template}

    =form_for(@template) do |f|
      .form-group
        =f.label :name
        =f.text_field :name, class: 'form-control'
        %p.help-block
          any name

      .form-group
        =f.label :body
        =f.text_area :body, class: 'form-control'
        %p.help-block
          template body

      .form-group
        =f.submit 'Create', class: 'btn btn-info'